import assert from 'node:assert/strict'
import { test } from 'node:test'
import { armBody, subjectBody } from './academics-body.ts'

test('an unassigned form teacher is sent, so the arm can be cleared', () => {
  // Left out entirely, the endpoint would keep whoever is already on the arm.
  assert.equal(armBody({ arm_name: 'JSS1 A' }).class_teacher_id, '')
  assert.equal(armBody({ arm_name: 'JSS1 A', class_teacher_id: '14' }).class_teacher_id, 14)
})

test('only the three statuses the API knows are sent', () => {
  assert.equal(armBody({ arm_name: 'A', armstatus: 'Archived' }).status, 'archived')
  assert.equal(armBody({ arm_name: 'A', armstatus: 'Retired' }).status, undefined)
  assert.equal(armBody({ arm_name: 'A' }).status, undefined)
})

test('an empty description is dropped rather than blanking the arm', () => {
  assert.equal(armBody({ arm_name: 'A', arm_description: '   ' }).arm_description, undefined)
})

test('a subject code left empty is generated by the API, not sent blank', () => {
  assert.equal(subjectBody({ name: 'Mathematics' }).subjectcode, undefined)
  assert.equal(subjectBody({ name: 'Mathematics', subjectcode: 'mth ' }).subjectcode, 'mth')
})

test('a credit load only goes when it is a real number', () => {
  assert.equal(subjectBody({ creditload: '3' }).creditload, 3)
  assert.equal(subjectBody({ creditload: '' }).creditload, undefined)
  assert.equal(subjectBody({ creditload: '0' }).creditload, undefined)
  assert.equal(subjectBody({ creditload: 'three' }).creditload, undefined)
})
