import type { CollectionDef } from '@/features/collections/types'
import { historyTab } from './history'

export const courses: CollectionDef = {
  id: 'courses',
  path: '/student/courses',
  kicker: 'Learning',
  title: 'My courses',
  description:
    'The ten subjects you are registered for this term, and who teaches each.',
  action: 'Download timetable',
  searchHint: 'Search subject',
  footer: '7 of 10 subjects shown',
  emptyTitle: 'No courses yet',
  emptyBody: 'Your subjects appear here once the office registers you for them.',
  noun: 'course',
  nameKey: 'name',
  tabs: historyTab,
  columns: [
    { key: 'code', label: 'Code', cardRole: 'title' },
    { key: 'name', label: 'Subject', cardRole: 'subtitle' },
    { key: 'teacher', label: 'Teacher' },
    { key: 'periods', label: 'Periods / wk', align: 'right' },
    { key: 'ca', label: 'CA so far', align: 'right' },
  ],
  rows: [
    { id: 'c-1', code: 'MTH', name: 'Mathematics', teacher: 'C. Nnaji', periods: '8', ca: '26 / 30' },
    { id: 'c-2', code: 'ENG', name: 'English Language', teacher: 'A. Mohammed', periods: '6', ca: '24 / 30' },
    { id: 'c-3', code: 'BIO', name: 'Biology', teacher: 'R. Obiora', periods: '4', ca: '22 / 30' },
    { id: 'c-4', code: 'CMP', name: 'Computer Studies', teacher: 'E. Duru', periods: '3', ca: '27 / 30' },
    { id: 'c-5', code: 'CHM', name: 'Chemistry', teacher: 'O. Balogun', periods: '4', ca: '19 / 30' },
    { id: 'c-6', code: 'PHY', name: 'Physics', teacher: 'O. Balogun', periods: '4', ca: '21 / 30' },
    { id: 'c-7', code: 'GOV', name: 'Government', teacher: 'K. Musa', periods: '3', ca: '25 / 30' },
  ],
}

export const materials: CollectionDef = {
  id: 'materials',
  path: '/student/materials',
  kicker: 'Learning',
  title: 'Course materials',
  description: 'Notes, slides and past papers your teachers have shared.',
  action: 'Download all',
  searchHint: 'Search material',
  footer: '6 of 41 materials',
  emptyTitle: 'Nothing shared yet',
  emptyBody:
    'Notes, slides and past papers appear here as your teachers share them.',
  noun: 'material',
  nameKey: 'title',
  tabs: historyTab,
  columns: [
    { key: 'title', label: 'Material', cardRole: 'title' },
    { key: 'subject', label: 'Subject', cardRole: 'subtitle' },
    { key: 'type', label: 'Type' },
    { key: 'size', label: 'Size', align: 'right' },
    { key: 'added', label: 'Added' },
  ],
  rows: [
    { id: 'm-1', title: 'Quadratic equations — worked examples', subject: 'Mathematics', type: 'PDF', size: '1.8 MB', added: '18 Nov' },
    { id: 'm-2', title: 'Cell structure diagrams', subject: 'Biology', type: 'PDF', size: '3.4 MB', added: '15 Nov' },
    { id: 'm-3', title: 'Spreadsheet basics — slides', subject: 'Computer Studies', type: 'PPTX', size: '5.1 MB', added: '14 Nov' },
    { id: 'm-4', title: 'Indices past questions 2019–2024', subject: 'Mathematics', type: 'PDF', size: '2.2 MB', added: '11 Nov' },
    { id: 'm-5', title: 'Comprehension passages set 3', subject: 'English Language', type: 'DOCX', size: '620 KB', added: '08 Nov' },
    { id: 'm-6', title: 'Periodic table reference', subject: 'Chemistry', type: 'PNG', size: '410 KB', added: '04 Nov' },
  ],
}

export const timetable: CollectionDef = {
  id: 'timetable',
  path: '/student/timetable',
  kicker: 'Learning',
  title: 'My timetable',
  description: 'Your periods for the week, in order.',
  action: 'Download PDF',
  searchHint: 'Search subject or day',
  footer: '8 periods shown · Monday to Friday',
  emptyTitle: 'No periods scheduled',
  emptyBody: 'Your timetable appears here once the office publishes it.',
  noun: 'period',
  nameKey: 'subject',
  tabs: historyTab,
  columns: [
    { key: 'day', label: 'Day', cardRole: 'title' },
    { key: 'time', label: 'Time', cardRole: 'subtitle' },
    { key: 'subject', label: 'Subject' },
    { key: 'teacher', label: 'Teacher' },
    { key: 'room', label: 'Room' },
  ],
  rows: [
    { id: 'tt-1', day: 'Monday', time: '08:00 – 08:40', subject: 'Mathematics', teacher: 'C. Nnaji', room: 'Block B, Rm 4' },
    { id: 'tt-2', day: 'Monday', time: '08:40 – 09:20', subject: 'English Language', teacher: 'A. Mohammed', room: 'Block A, Rm 2' },
    { id: 'tt-3', day: 'Monday', time: '10:00 – 10:40', subject: 'Biology', teacher: 'R. Obiora', room: 'Lab 2' },
    { id: 'tt-4', day: 'Tuesday', time: '08:00 – 08:40', subject: 'Chemistry', teacher: 'O. Balogun', room: 'Lab 1' },
    { id: 'tt-5', day: 'Tuesday', time: '11:20 – 12:00', subject: 'Computer Studies', teacher: 'E. Duru', room: 'ICT Suite' },
    { id: 'tt-6', day: 'Wednesday', time: '09:20 – 10:00', subject: 'Physics', teacher: 'O. Balogun', room: 'Lab 3' },
    { id: 'tt-7', day: 'Thursday', time: '08:40 – 09:20', subject: 'Government', teacher: 'K. Musa', room: 'Block A, Rm 5' },
    { id: 'tt-8', day: 'Friday', time: '10:00 – 10:40', subject: 'Mathematics', teacher: 'C. Nnaji', room: 'Block B, Rm 4' },
  ],
}
